debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        validator:
          apply_to_ddl: true

  h2:
    console:
      enabled: false
