debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: true

  h2:
    console:
      enabled: false
