debug: true

spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: osm_mosques
      password: osm_mosques
      jdbc-url: jdbc:mariadb://mariadb:3306/osm_mosques

osm:
  data:
    location: /home/osm_mosques/osmdata/by-quadtile/current
